import type {
  ParsedSource,
  SourceCodecRegistry,
  SourcePayload,
} from '../codec/types.ts';
import type { PageExtensionRuntimeAvailability } from '../extensions/types.ts';
import type { NormalizedPageSpec } from '../pagespec/types.ts';
import type { PageRegistry, PageRegistrySnapshot, ScopeManifest } from '../registry/types.ts';

export interface PageEnvelopeCodec {
  readonly id: string;
  readonly mediaType?: string;
  readonly version: string;
}

export interface PageEnvelopeCachePolicy {
  readonly maxAgeSeconds: number;
  readonly staleWhileRevalidateSeconds?: number;
}

export interface PageEnvelopeSignature {
  readonly algorithm: 'Ed25519';
  readonly keyId: string;
  /** Verifier-owned base64url data; the core never resolves keys from a page. */
  readonly value: string;
}

/** Raw source delivery metadata. It never contains an execution plan or function. */
export interface PageEnvelope {
  readonly cache: PageEnvelopeCachePolicy;
  readonly codec: PageEnvelopeCodec;
  readonly documentId: string;
  readonly expiresAt?: string;
  readonly issuedAt?: string;
  readonly pageSpec: 'domily.page/v1';
  readonly payload: SourcePayload;
  readonly payloadHash: string;
  readonly revision: number;
  readonly schema: 'domily.envelope/v2';
  readonly signature?: PageEnvelopeSignature;
}

export interface PageEnvelopeSignatureInput {
  readonly bytes: Uint8Array;
  readonly envelope: PageEnvelope;
}

export type PageEnvelopeSignatureVerifier = (
  input: PageEnvelopeSignatureInput,
) => boolean | Promise<boolean>;

export interface PageEnvelopeCacheEntry {
  /** Audit metadata only. Cache freshness is derived from signed envelope times. */
  readonly acceptedAt: number;
  readonly envelope: PageEnvelope;
  /** Audit/cache provenance only; every hit is parsed and normalized again. */
  readonly registryFingerprint: string;
}

/** The signed identity used by an atomic cache compare-and-swap operation. */
export interface PageEnvelopeCacheVersion {
  readonly payloadHash: string;
  readonly revision: number;
}

/**
 * Persistence boundary. Implementations must clone values at every edge and
 * implement compareAndSwap atomically for a namespace/document pair.
 */
export interface PageEnvelopeStore {
  compareAndSwap(
    namespace: string,
    documentId: string,
    expected: PageEnvelopeCacheVersion | undefined,
    entry: PageEnvelopeCacheEntry,
  ): boolean | Promise<boolean>;
  delete(namespace: string, documentId: string): void | Promise<void>;
  get(namespace: string, documentId: string): PageEnvelopeCacheEntry | undefined | Promise<PageEnvelopeCacheEntry | undefined>;
}

export interface PageEnvelopeFetchContext {
  readonly documentId: string;
  readonly signal?: AbortSignal;
}

export type PageEnvelopeFetcher = (
  context: PageEnvelopeFetchContext,
) => unknown | Promise<unknown>;

export interface PageDeliveryLoadOptions {
  readonly fetcher?: PageEnvelopeFetcher;
  readonly signal?: AbortSignal;
}

/**
 * A host-owned public scope contract visible to delivery validation. Extension
 * scopes are per-mount runtime output and are checked through runtime
 * availability instead of being supplied as static host state.
 */
export interface PageDeliveryScope {
  readonly manifest: ScopeManifest;
}

export interface PageDeliveryClientOptions {
  /** Required tenant/app partition; prevents cross-environment cache reuse. */
  readonly cacheNamespace: string;
  readonly codecs: SourceCodecRegistry;
  readonly fetcher?: PageEnvelopeFetcher;
  readonly maxCacheAgeSeconds?: number;
  readonly maxPayloadBytes?: number;
  readonly maxStaleWhileRevalidateSeconds?: number;
  readonly now?: () => number;
  /**
   * Local deployment view only. Delivery verifies it but never executes an
   * extension runtime while parsing, revalidating, or reading cache.
   */
  readonly extensionRuntimes?: PageExtensionRuntimeAvailability | (() => PageExtensionRuntimeAvailability);
  readonly registry: PageRegistry | PageRegistrySnapshot | (() => PageRegistrySnapshot);
  /**
   * Host public scope contracts, never their values. Extension-owned scopes
   * are generated by trusted runtime activation only at PageHost.mount().
   */
  readonly scopes?: readonly PageDeliveryScope[] | (() => readonly PageDeliveryScope[]);
  readonly store?: PageEnvelopeStore;
  /** Development-only opt-in. Remote envelopes otherwise need a signature. */
  readonly allowUnsigned?: boolean;
  readonly verifySignature?: PageEnvelopeSignatureVerifier;
}

export type PageDeliverySource = 'cache' | 'network' | 'stale-cache';

export interface DeliveredPage {
  readonly acceptedAt: number;
  readonly envelope: PageEnvelope;
  readonly page: NormalizedPageSpec;
  readonly parsed: ParsedSource;
  readonly registryFingerprint: string;
  readonly source: PageDeliverySource;
  readonly stale: boolean;
}

export interface PageDeliveryClient {
  accept(envelope: unknown): Promise<DeliveredPage>;
  getCached(documentId: string): Promise<DeliveredPage | undefined>;
  load(documentId: string, options?: PageDeliveryLoadOptions): Promise<DeliveredPage>;
  revalidate(documentId: string, options?: PageDeliveryLoadOptions): Promise<DeliveredPage>;
}

export class PageDeliveryError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly causeValue?: unknown,
  ) {
    super(message);
    this.name = 'PageDeliveryError';
  }
}
