name: playground deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        bun-version: [1.2.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: se/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          npm install pnpm@latest -g
          pnpm install

      - name: Build playground
        run: pnpm build:playground

      - name: Deploy to playground branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/domily-playground/dist
          branch: playground
          force_orphan: true
