name: playground deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          curl -fsSL https://bun.sh/install | bash
          { ln -s $HOME/.bun/bin/bun /usr/bin } || { sudo ln -s $HOME/.bun/bin/bun /usr/bin }
          npm install pnpm@latest -g
          pnpm install

      - name: Build playground
        run: pnpm build:playground

      - name: Deploy to playground branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/domily-playground/dist
          branch: playground
          force_orphan: true
